version: "3.4"

services:
  springbootrediscacheservice:
    image: springbootrediscacheservice
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
volumes:
  targetjava:
